### ISSUE TITLE
Crash with CoFHCore

### ISSUE THREAD

**Issue by miuirussia** [wildex999/TickDynamic#13]
Crashes with any version of CoFHCore above CoFHCore-[1.7.10]3.0.0RC2-201

LOG:
http://pastebin.com/6LnfRF5G

output_original.log:
http://pastebin.com/hiez90pV

**Comment by wildex999** [comment]
It seems to be a patching conflict. It may be that it's incompatible with another mod patching the same place, or the forge version(you did use the forge download, right?).
I'm not home right now, so I can't fix it.
 I'll look into it once I get home in a few days =)

**Comment by wildex999** [comment]
This has now been fixed for version 0.1.5, which can be downloaded from the project page =)

**Comment by ajthemacboy** [comment]
When will these changes be added to TickDynamic cauldron?
