### ISSUE TITLE
FTB Infinity help.

### ISSUE THREAD

**Issue by Zendrex** [wildex999/TickDynamic#16]
I know this github is only for bugs really, but though I could get some support from the mod developer himself.

I have a few FTB servers I run, I used your mod overnight and it helped, however I have no clue how to optimize it with 10 different worlds. I am running FTB infinity.

**Comment by Katelyn-SN** [comment]
Optimizing 10 different worlds? Make a server per world. Minecraft servers are single threaded they can not and will not support that many worlds properly. We split our servers up per world and it helps with performance significantly.

**Comment by Zendrex** [comment]
I would do something like that, but because of quarrys, etc I wouldnt be able to. :/

**Comment by Katelyn-SN** [comment]
Well thats your only option to improve performance. Minecraft servers are not meant for that workload.
