### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Flukethoughts** [wildex999/TickDynamic#17]
I was wondering will you be updating the cauldron version anytime soon?

**Comment by wildex999** [comment]
Hello,
What do you mean? Have you found a bug in the current Cauldron version?
So far the only non-Cauldron updates have been to fix problems which doesn't appear in the Cauldron version.

As for version 0.2, that is on hold until I start playing Minecraft again.

**Comment by Flukethoughts** [comment]
The current version of tickdynamic doesn't work with cauldron 1370
http://tcpr.ca/cauldron

And we are currently needing to use that version to fix a few bugs

**Comment by solomon56** [comment]
I'm running into this issue as well TickDynamic not patching the latest methods from forge 1395 or any cauldron version past 1307

**Comment by Zilacon** [comment]
It also does not work on KCauldron.

**Comment by Katelyn-SN** [comment]
For those wanting KCauldron support @thomas15v has converted this mod to mixins and as far as our testing goes it is currently working.

https://github.com/ShadowNode/TickDynamic/releases
