### ISSUE TITLE
TickDynamic does not let the server boot.

### ISSUE THREAD

**Issue by Zilacon** [wildex999/TickDynamic#18]
Using cauldron build 1388 for 1.7.10 and when i place tick dynamic into my mods folder and start the server it says:

```
A problem occurred running the server launcher.
```

Any way to fix this?

**Comment by Beelzaboss** [comment]
Same issue, please help ;( I am using KCauldron

**Comment by louisw22** [comment]
It could be an issue with KCauldron, I have the same Problem

**Comment by Katelyn-SN** [comment]
Yeah it's a patching error with the changes made by the recent updates to forge. Considering we have not heard from the Dev in a while this project is pretty much dead.

**Comment by louisw22** [comment]
It's a shame

**Comment by wildex999** [comment]
Hello,
I have been(And still is) busy with other projects at the moment. I will probably come back to update this at a later time when I get back into Minecraft.

Last I heard Cualdron was done, and I thus stopped updating the mod for it.
I haven't heard of KCauldron before now, so I might take a look at making it compatible at a later date.

For now I will upload the source code, so anyone who wants to can continue updating it if they want to.

**Comment by Katelyn-SN** [comment]
For those wanting KCauldron support @thomas15v has converted this mod to mixins and as far as our testing goes it is currently working.

https://github.com/ShadowNode/TickDynamic/releases

**Comment by Zilacon** [comment]
@Katelyn-SN While i love the work of @thomas15v I have tested his version of TickDynamic and it was killing my servers more then helping. Eventually everything slowed down to a crawl after about 2 hours of uptime. Even when i set the splices for specific worlds to 300+ those worlds still slowed down to a crawl after 2 hours. In the end it is impossible to have this running on my servers using KCauldron for any length of time.

Players Online: 2-5
Example: Beyond the 2 hours it would take a powered furnace from TE 8 minutes to smelt 1 thing.

**Comment by thomas15v** [comment]
Yeah I can't help it. Probably cauldron or minecrafts tick calculation system has been overwritten in my patch. @Katelyn-SN can you please stop throwing beta stuff around :smile:. My test was just to see if mixins where capable of doing patches like these.
