### ISSUE TITLE
A problem occurred running the server launcher. (Log)

### ISSUE THREAD

**Issue by Beelzaboss** [wildex999/TickDynamic#20]
Hi there, I am having a issue trying to start up with TickDynamic using the latest KCauldron, Here is my log for early startup. KCauldron is a 1.7.10 fork of Cauldron that supports newer versions of Forge, It can be found here: http://tcpr.ca/cauldron.

Here is my early startup log, hope it may help :smile: 

http://pastebin.com/ne28xd78 *New Log

**Comment by Katelyn-SN** [comment]
This has been reported many times already but it seems it might be safe to say this mod is pretty much abandoned.

**Comment by wildex999** [comment]
Hello,
Thank you for the link and log, as that will help when implementing support.
However, currently I don't have time to update this mod. I will take a look at it at a later date when I have time.

I will however upload the source for anyone who are willing to take a shot at it.

**Comment by Katelyn-SN** [comment]
If you put up the source expect it to be fixed within days.

**Comment by wildex999** [comment]
The mod is quite complex as I do bytecode modifications, and implemented my own "language" for writing patches. =P

The code is up now. Master is the latest 0.1.x version, while my work on 0.2.x is in it's own branch.

**Comment by Katelyn-SN** [comment]
For those wanting KCauldron support @thomas15v has converted this mod to mixins and as far as our testing goes it is currently working.

https://github.com/ShadowNode/TickDynamic/releases

Also what did i say @wildex999 a few days? :P

**Comment by thomas15v** [comment]
Calm down @Katelyn-SN XD. I just got it working and I am almost sure that we are overwriting some cauldron features. I still need to filter the mixins better and use `@Inject` stuff instead of `@overwrite`.

**Comment by wildex999** [comment]
Color me impressed xD Tho it is painful watching my patcher being removed :p

@thomas15v I am however curious about how well Mixins handle collisions with other coremods? Or event just small updates that change the name of structure slightly. 
I know I had to take into account CoFHCore patching the exact same spot in World, and I had written my patcher to be able to.

Also, in my work on 0.2 I was moving away from patching World so much, and instead was just going to replace the TileEntity and Entity list with my own custom ArrayList, as some other mods have done. Might want to look into that too :)

Anyway, Good work =)

**Comment by thomas15v** [comment]
Mixins still has issues with other coremods sadly enough. The "update" I made will probably be incompatible with other mods. The way to solve that is using @injects. 

I don't think mixins supports changing the type field. But I think i might change the tick skipping way with breaking the loop. Changing loops with mixins simply doesn't work yet :cry:.

And sorry for removing the patcher. I just didn't felt like learning this xD. I am sure it was nicely put together. I just didn't had the time to figure it out :wink:.

**Comment by Polyana-Fontes** [comment]
@thomas15v  I could help with mixins, however I didn't find any documentation or example code using `@Inject`, when I need to patch I still use forge class transformers and I feel like I'm doing the old and time-hungry way just because I couldn't understand how to inject code without overwritting the entire method using mixin. Do you know any example code? If you share it I might help you in few days, I can work with ASM :P
