### ISSUE TITLE
Not compatible with kCauldron

### ISSUE THREAD

**Issue by tenten8401** [wildex999/TickDynamic#21]
I can't get it to work with kCauldron to save my life.
Please take a look.

**Comment by spannerman79** [comment]
https://github.com/ShadowNode/TickDynamic/releases

**Comment by UnixRonin** [comment]
I just discovered TickDynamic myself and said "WHEEEEE!!!!!!!"  Then discovered the exact same problem.

Compatibility with KCauldron-1.7.10-1448.121-server or newer would be hugely appreciated.  (As in I'd be willing to help fund it happening.)

**Comment by wildex999** [comment]
Yeah, sorry about no KCauldron compatibility. I'm thinking of playing some more Minecraft again, so I will probably have a look at making the mod compatible some time soon, when I have time.

**Comment by UnixRonin** [comment]
That would be awesome.  Proactive tick-time rationing is something modded Minecraft has needed for a long time.

**Comment by spannerman79** [comment]
:+1:

**Comment by tenten8401** [comment]
Maybe if your ambitious enough you could keep this going for 1.7.10 as well... Even attempting to make it kCauldron compatable is a big plus though.

**Comment by Y0ungSandwich** [comment]
Would absolutely love to see a Kcauldron compatible version as well. I got so excited when I saw this mod then saddened when I saw the server not launch. :P

**Comment by wildex999** [comment]
Have some progress lately, the new implementation for 0.2.0 seems to be working fine on normal Forge so far, using the new patching method it should in theory also work for Cauldron and kCauldron with very few modifications.

I have a bit work left to ensure the timing calculation works correctly, and the commands and output needs some more work.
I'll try to have something for testing soon.

Some housecleaning of combining all the issues about compatibility:
https://github.com/wildex999/TickDynamic/issues/17
https://github.com/wildex999/TickDynamic/issues/18
https://github.com/wildex999/TickDynamic/issues/20

**Comment by spannerman79** [comment]
I assume that you already know that the git repo for KCauldron is at https://gitlab.prok.pw/KCauldron/KCauldron .

Once you have a testing build I'm more then willing to test @wildex999. While using KCauldron of course :smile:

**Comment by UnixRonin** [comment]
I also would be glad to test on KCauldron.  I already have a test server online.  I'm running KCauldron-1.7.10-1448.121-server at the moment, but I have KCauldron-1.7.10-1517.168-server and KCauldron-1.7.10-1614.174-server downloaded (but not yet tested with my modpack).

(Actually just testing and updating to 1.7.10-1614.174 right now.)

**Comment by wildex999** [comment]
Been looking at the KCauldron source code for the part which is pertinent for TickDynamic's work.
It seems that KCauldron has a very basic limiter implemented lately, which essentially stops ticking Entities/TileEntities if the whole loop uses more than x milliseconds(Default 50ms it seems = One world tick).

This might be a problem if the limiter decides to break off in the middle of TickDynamic's ticking, as TickDynamic would not notice that the ticking has ended, and continue timing the last Entity/TileEntity.
At best this would cause mistiming and weird TPS, at worst it would crash the server.

KCauldron has also removed the nice Iterator loop that was used for TileEntities before, replacing it with a for-loop.
I can still make TickDynamic work with this, but it will mean that I have to maintain a version especially for KCauldron.
I'll continue working on it and see how it goes =)

**Comment by spannerman79** [comment]
> Been looking at the KCauldron source code for the part which is pertinent for TickDynamic's work.

Did you see at which commit it was changed?

**Comment by wildex999** [comment]
The limiter was added here: https://gitlab.prok.pw/KCauldron/KCauldron/commit/4496eada0ad96669a6d5556231921c32de6a7034

However, I think I can work around it by (ab)using the profiler a bit =P
I think I can make it play nice with the limiter, but I will still recommend server owners to turn off the limit(Set it to a unlikely high value)

**Comment by UnixRonin** [comment]
I assume you mean set KCauldron's limit to an unlikely high value.  How do we do that?  I'm not seeing anything that looks obviously relevant in my kcauldron.yml file, which is where I assume it would be.  However, kcauldron adding tick-limiting might be why after upgrading kcauldron and about half a dozen mods, my total tick CPU time dropped from 65-70ms down to 38-42ms.

**Comment by wildex999** [comment]
The config options seems to have been added under spigot.yml for some reason:
   max-tick-time:
      tile: 50
      entity: 50

It defaults to 50 ms, which essentially means that if it takes more than 50 ms to update just Entities or just TileEntities, it will simply stop the updates at that point, and continue from there on the next tick. It's the same idea as TickDynamic, but it's a hard limit instead of a dynamic one.
Right now, it seems to be more of a way to stop the server from crashing due to long-ticking Entities, rather than trying to maintain any decent TPS(One Tick is 50 ms).

**Comment by spannerman79** [comment]
I already set both to 1000 due to some spigot timing issues

More information can be read via http://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/

**Comment by wildex999** [comment]
Ok, I have an early KCauldron build ready, using the new Grouping system.
So far I have tested it on a vanilla KCauldron server, and KCauldron on FTB Infinity.
I have pointed out some known issues on the release page.

I'm not currently running a Minecraft server myself, so I don't have the ability to test it out on a fully running server with stuff happening. I would really appreciate it if any of you would be able to test it out, and provide some feedback on problems =)
Note: It is buggy, and will most likely crash at some point. I recommend doing a world backup(As you should be doing anyway)

Release: https://github.com/wildex999/TickDynamic/releases/tag/KCauldron_0.2.0-dev1

**Comment by spannerman79** [comment]
I could give you access to the repo that the unofficial builds were built from @wildex999 

Those builds were a little more stable then what the current builds are - as you would have seen by looking at the kcauldron issue tracker.

**Comment by wildex999** [comment]
Hehe. The only problem I have found when using TickDynamic with KCauldron so far, is that it randomly decides that it can't remove an entity. I'm pretty sure that is a problem with TickDynamic, I just haven't found the reason yet.

I have also put out TickDynamic dev builds for Forge 1.7.10 and Forge 1.8 now, so you guys are free to test it out. Development builds are under "Resources" on github.

I'm moving the coming week, so I won't do much work on TickDynamic during that time. Feel free to post a new issue if you encounter any problems while testing it, and I'll take a look when I can =)

**Comment by spannerman79** [comment]
> is that it randomly decides that it can't remove an entity. I'm pretty sure that is a problem with TickDynamic, I just haven't found the reason yet.

Well I've added you in anyway - you should have access.  Feel free to compile or you can grab pre-compiled from the release tab :stuck_out_tongue: 

You'll be able to see from the commit history.  And if in fact tickdynamic was able to remove an entity without an issue on the unofficial builds then its something that wasn't reverted back or was added at commit https://gitlab.prok.pw/KCauldron/KCauldron/commit/f722fccdcea1a0faec61c1bd72d5dd56b0c17c14

**Comment by wildex999** [comment]
Now KCauldron is just out to screw with TickDynamic -_-
https://gitlab.prok.pw/KCauldron/KCauldron/commit/097252b5bf8fc95b4ceb059bdff83ca992f13dbe

**Comment by tenten8401** [comment]
oh my

**Comment by spannerman79** [comment]
> Now KCauldron is just out to screw with TickDynamic -_-

Sigh.... I know what Prototik is trying to do but that doesn't help you @wildex999 

What about the unofficial repo that I gave you access to?   That was built from kcauldron builds 152 - and also on Yives mirror

**Comment by wildex999** [comment]
I haven't had the time to check it out yet, moving tomorrow and won't have access to my desktop until then end of the week.

The top google result(For me at least) for KCauldron, is https://gitlab.prok.pw/KCauldron/KCauldron. So that is what I'm developing against right now, as I assume that is the version most people will use.

**Comment by spannerman79** [comment]
True - although it looks like build 152 (or builds based on 152) seem to have the least issues.  Anything onwards ... well here are some issues so far

Just now - https://gitlab.prok.pw/KCauldron/KCauldron/issues/301 (most recent)

Ongoing - https://gitlab.prok.pw/KCauldron/KCauldron/issues/289

**Comment by wildex999** [comment]
KCauldron has the same problem Cauldron did. It's a mix of so many different servers, with it's own addition of 'fixes', that things will just break at every corner. 
All it takes is a mod which makes a certain assumption that KCauldron does not.

Though https://gitlab.prok.pw/KCauldron/KCauldron/issues/289 does seem kinda bad.

**Comment by spannerman79** [comment]
> Though https://gitlab.prok.pw/KCauldron/KCauldron/issues/289 does seem kinda bad.

Yeah - thats why many server admins have kept to 152 builds or have branched off their own builds based on 152 - as you prob have seen yourself :stuck_out_tongue: 

I'm staying with kcauldron until the majority of the mods that I use (80%) have moved over to 1.8/1.9 then I'll be moving to [SpongeForge](http://files.minecraftforge.net/spongepowered)

**Comment by spannerman79** [comment]
Well one use has moved back to one of the builds I did https://gitlab.prok.pw/KCauldron/KCauldron/issues/289#note_2356 - for now.

You could state that you support up to build 152 while within `spigot.yml` the options under `max-tick-time` **must** be set to `1000` or higher.

**Comment by spannerman79** [comment]
I've made a couple of updates that should be more in line to what would be ideal for tickdynamic (via https://github.com/spannerman79/KCauldron/releases) that you have access to @wildex999

**Comment by wildex999** [comment]
Yeah, I noticed. Github informs me when you do releases on there.

However, as I mentioned before, I can't base TickDynamic on your builds, as they are not what most people will find when they search for kCauldron for their servers =(

**Comment by linkinkov** [comment]
@spannerman79 can you give me access to you rep?

**Comment by spannerman79** [comment]
@wildex999 I suggesting closing this issue - you have released dev builds which should be tested.

**Comment by wildex999** [comment]
Yeah you are right.
Closing, use the dev issues for any questions/feedback instead.
