### ISSUE TITLE
Webpage blocked by major search engines and security software.

### ISSUE THREAD

**Issue by ianc1215** [wildex999/TickDynamic#22]
I could not find any other way to contact you regarding this.

Your website looks like it has a serious issue. Google and Microsoft prevent access to the page from browsers. Even when I tell Google to go there anyway my anti-virus flips out.

I was not sure you were aware of this but someone might have buried something in your webpage which needs to be addressed.

**Comment by wildex999** [comment]
Hey, thank you for taking the time to inform me of this. I kinda left some Advertisement code on the webpage way back, and it seems to have gone bad lately. I also got popups and stuff when I visited just now =/

I have removed the advertisement code now, so it should all work well.
