### ISSUE TITLE
kCauldron - Report on performance of 0.2.0-dev1

### ISSUE THREAD

**Issue by spannerman79** [wildex999/TickDynamic#24]
I've been running this on an actual "Open Beta" type server for awhile now.  The label of Open Beta is so that my users know not to expect anything to stay the same and that there **will** be issues.  Even `rm -rf world/` :smiling_imp: 

Overall;

Yes there is _some_ world leakage but if anyone that runs kcauldron or a forge based server for longer then 6ish hours without restarting needs to be shot and buried lol

About the Group reload issue - I've known for quite some time that if you make any sort of config change its best to restart the server anyway. Give a chance for both mods and plugins to adapt to the new changes

The "Entity removal de sync!" console spam - reload fixes this and only happens when running your mod for the very first time and there was no config file for your mod to load.  I consider that normal considering how the majority of other mods & plugins work - they won't work correctly on their maiden run :stuck_out_tongue: 

Versions used: Both official via https://gitlab.prok.pw/KCauldron/KCauldron and the builds that you have access to @wildex999 :smile: 

On both, 

`max-tick-time` for both ``tile` & `entity` set to `1000`

Noticeable issues:

None.  Although a test of one server with average users of 20 (per day being online for longer then one hour) is not really a large enough test to mark an alpha release as beta

**Comment by wildex999** [comment]
Thank you for taking the time to test and write about it =)

I'm hoping to get rid of world leakage before the final release. Some things still hold a reference to the world after they are unloaded.

I'm currently working on getting group reload to work. I want it to work correctly, as I want to allow for testing different group values without needing a full server restart(Which usually takes a while on modded servers.)
The problem I'm working on is properly moving around the already loaded Entities/TileEntities when groups are added/removed/moved, without hanging up the server or causing other problems.

The 'Entity removal de sync' is a weird bug, which should not happen. I will have to take a further look into that, as It can have lasting effects, by keeping a removed entity in the world(Even if it's marked as dead and will not tick).
That you only got it before the config was created will help me a lot in tracking down the cause.

How much load was the server under while you tested? Did the Dynamic Ticking have to kick in by slowing stuff?
It's great to know it's stable at least, so many moving parts that can cause problems =P

**Comment by spannerman79** [comment]
> How much load was the server under while you tested?

I'd say I have a fairly healthy server (16GB ram, Java 8, ~3.5Gkz CPU's SSD) so it can handle almost everything.

On purpose myself and some friends created some ticking tile entities (hoppers being activated via http://ftbwiki.org/Redstone_Clock) dropping into chests and those feeding into vanilla furnaces.

Even did the worst thing you could think of - force create phantom chunk loading, or my favourite new term now - _chunk churn_ ( if you want to read more about it https://www.reddit.com/r/feedthebeast/comments/3lfjpp/1710_post_mortem_investigating_mystery_chunk/ )

Only then did TickDynamic kick in and slow down the hoppers and furnaces. TPS was kept at around 17ish.  Shudown, removed TickDynamic and as a test kept the same world and same setup and started the server up again.  Ohh not good, TPS wise without TickDynamic was less then 10 before i killed the process via ssh LOL.

I did say I did the worst thing you could think of server wise :tongue: 

//offtopic but related

I mentioned your mod here https://github.com/TCPR/KCauldron/issues/52#issuecomment-177550961 :smile:

**Comment by wildex999** [comment]
Hehe, Chunk Churn indeed.
Chunk unloading/loading and World Generation usually happens in bursts. Tick Dynamic does time management on averages, and will thus not be able to accurately account for burst work. It should still be able to smooth it out, as it seems to have done in this case =)

It seems then that it works as it should at least =D
I will probably set up a public server of my own at some point, to have a good environment to fully test my mods on =)

Thank you for your feedback!

**Comment by spannerman79** [comment]
A side note - instead of giving releases as rar's you could upload the jar directly - this makes it easier to `wget` directly onto the server via ssh

**Comment by Shybella** [comment]
I'll give you my body If you can keep this alive.

**Comment by wildex999** [comment]
@Shybella I'll try to keep the kCauldron alive at least until FTB comes out with a stable 1.8 mod pack =)

@spannerman79 Yeah, I'll do that for future releases.

**Comment by wildex999** [comment]
I think I have fixed the "Entity removal desync!" issue.
It seems that I didn't correctly set-up the "ungrouped" group, so entities which belonged to the "default" group, except in the overworld, were not being removed at all.

This might also have caused other problems(Like world corruption in worst case, as the entity would still "exist", just be marked dead and not ticking)

I'll do some more testing and probably release another KCauldron dev version soon.

**Comment by spannerman79** [comment]
dev-3 released. Closing this issue.
