### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Hazado** [wildex999/TickDynamic#3]
Hope this helps fix whatever issue I have, let me know if you need any more info
http://pastebin.com/Xdc3NUhk

**Comment by wildex999** [comment]
You closed the issue, did you figure out the problem?
The crash report did give very little information.
Is seems you're using Java 8, which I haven't tested, so that might be the problem.
Did you run a modpack?(If so, which one and which version?)
If not, what mods are you using?

**Comment by Hazado** [comment]
Yes figured it out. Duplicate mods in the mod folder. Was my mistake, removed the duplicates and server started fine. Haven't seen any issues yet, running the default configs. Will let you know any issues I do run into

**Comment by wildex999** [comment]
Great to hear its's running with Java 8 too, don't hesitate to write if there's anything that isn't working =)
