### ISSUE TITLE
[14:04:16] [Server thread/WARN] [tickdynamic]: Trying to remove: null but not instanceof class EntityObject

### ISSUE THREAD

**Issue by alxcool** [wildex999/TickDynamic#33]
Single player 1.12.2 (old launcher) on forge 2705.
TickDynamic-1.12.2-1.0.1
What does that mean? And why my minecraft console write that line 20 time per sec, as soon as I load a map?
_`[14:04:16] [Server thread/WARN] [tickdynamic]: Trying to remove: null but not instance of class EntityObject`_

Minecraft crashed while I was sorting a few items (open/close many chests). The game paralyzed and it was unable to create a proper crash file. I had to close the program manually.

Note : I've tried to upload the latest.log, but 2G of lines make it bigger than 10mb.
Others mods who send a line from time to time is Aroma backup (b101), and the server can't keep up did the time have changed?

**Comment by alxcool** [comment]
Wrong project, sorry... How do I delete his?

**Comment by wildex999** [comment]
No problem, don't think you really can delete GitHub issues. 
I hope you find a solution to your problem :)
