### ISSUE TITLE
Crash with CoFHCore

### ISSUE THREAD

**Issue by Hazado** [wildex999/TickDynamic#5]
Crashes with any version of CoFHCore above CoFHCore-[1.7.10]3.0.0B9-109.

**Comment by wildex999** [comment]
Do you have a crash message or log output of the crash?

**Comment by wildex999** [comment]
I am able to boot both a Forge server and a Cauldron server using "CoFHCore-[1.7.10]3.0.0B9-110" and TickDynamic 0.1.3 without crash.
Does this happen on boot, or at a specific point?

**Comment by Hazado** [comment]
Um, try CoFHCore-[1.7.10]3.0.0B9-120.jar or CoFHCore-[1.7.10]3.0.0B9-116.jar.
I went from 109 to 116 and didn’t test any inbetween.

It happens on boot, right after you make your core edits

**Comment by wildex999** [comment]
ok, reproduced it. Seems to be a problem in my patcher, I will fix it =)

**Comment by Hazado** [comment]
Thanks, Wildex999!

**Comment by wildex999** [comment]
Ok, uploaded version 0.1.4, which fixes this crash =)

Thank you for taking the time to report this bug!
