### ISSUE TITLE
Per chunk ticking.

### ISSUE THREAD

**Issue by Katelyn-SN** [wildex999/TickDynamic#6]
Thought i might add this as a progress report.

**Comment by wildex999** [comment]
Currently I'm working on the ability to define groups, allowing you to set certain TE's/Entities to be given a different time slice, or making the not be slowed down at all.
For example, say you want to slow down Cows,Chickens and Pigs more than other Mobs, you will be able to do so.

I'm also working on adding the ability to time and limit per player.

Per chunk ticking I'm not entirely sure how to do yet, at least properly.

**Comment by Katelyn-SN** [comment]
What would be nice is per entity/tile entity or per chunk so if one user on the server is doing some really bad stuff everyone else is not effected all his things are just slowed way down.

**Comment by spannerman79** [comment]
The only way that i could see something like that happening if you use some sort of permission system.  Be it kcauldron, forgeessentials or even SpongeAPI but that wouldn't be exactly dynamic.

You could (for example) define a permission node to have x amount of slices for that node.  Would be more ideal for say those users that help contribute towards the running costs of the server over those that just come on to play.
