### ISSUE TITLE
Custom groups

### ISSUE THREAD

**Issue by wildex999** [wildex999/TickDynamic#8]
Allow for defining custom groups, that are either excluded from the slowing down, or have it's own defined time slices.

**Comment by wildex999** [comment]
This is currently the work in progress. 
This requires a bit of rewriting of the system I originally used, and takes a bit of time.
It will also pave the way for per-user accounting, which will come in 0.3.0, as each user will be a group.

**Comment by Slind14** [comment]
Would this allow per mod settings?

**Comment by wildex999** [comment]
Yes, you will be able to place every item, TileEntity, Entity etc. from a mod, inside a group.
